### ISSUE TITLE
歌曲下载失败

### ISSUE THREAD

**Issue by lancer-wang** [ZYKsslm/nonebot_plugin_zyk_music#4]
复现方式
qq点歌 无损音质 请跟我来
然后选2

**Comment by lancer-wang** [comment]
err log
>Traceback (most recent call last):
  File "/cobudy/omega-miya/bot.py", line 63, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_zyk_music/__init__.py", line 75, in _
    if info[0] is False:
TypeError: 'bool' object is not subscriptable

**Comment by ZYKsslm** [comment]
已修复，请更新插件

**Comment by ZYKsslm** [comment]
> 复现方式 qq点歌 无损音质 请跟我来 然后选2

对了，只有QQVIP支持选择音质，其他默认标准

**Comment by lancer-wang** [comment]
> > 复现方式 qq点歌 无损音质 请跟我来 然后选2
> 
> 对了，只有QQVIP支持选择音质，其他默认标准

可以了
