### ISSUE TITLE
qqvip点歌报错~

### ISSUE THREAD

**Issue by Cwlovecqt** [ZYKsslm/nonebot_plugin_zyk_music#5]
02-18 16:50:44 [INFO] nonebot_plugin_zyk_music | 开始下载'发如雪'，音源：qqvip
02-18 16:50:44 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_zyk_music) running complete
02-18 16:50:44 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_zyk_music) failed.
Traceback (most recent call last):
  File "c:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\program files\python\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\program files\python\lib\site-packages\nb_cli\handlers\deploy.py", line 23, in run_bot
    nonebot.run()
  File "c:\program files\python\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "c:\program files\python\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\program files\python\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\program files\python\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\program files\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\program files\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "c:\program files\python\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_zyk_music\__init__.py", line 105, in _
    info = await get_music(mode="data", source=source, name=name, proxies=proxies, br=br, path=path, n=n)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_zyk_music\work.py", line 71, in get_music
    return await vip_qq_download(name, n, br, path, proxies)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_zyk_music\work.py", line 369, in vip_qq_download
    async with AsyncClient(headers=headers, params=data, follow_redirects=True, timeout=None, proxies=proxies) as client:
  File "c:\program files\python\lib\site-packages\httpx\_client.py", line 1405, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "c:\program files\python\lib\site-packages\httpx\_client.py", line 1408, in <dictcomp>
    else self._init_proxy_transport(
  File "c:\program files\python\lib\site-packages\httpx\_client.py", line 1461, in _init_proxy_transport
    return AsyncHTTPTransport(
  File "c:\program files\python\lib\site-packages\httpx\_transports\default.py", line 275, in __init__
    elif proxy.url.scheme in ("http", "https"):
AttributeError: 'int' object has no attribute 'url'

**Comment by Agnes4m** [comment]
同样的报错

**Comment by ZYKsslm** [comment]
已解决
